
import React, { useState, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea"; // Added this import
import { Save, TestTube, HardDrive, Clock, Trash, Download } from "lucide-react";
import { StorageSettings as StorageSettingsEntity } from "@/api/entities";
import { logAuditAction } from "../utils/auditLogger";
import { useToast } from "@/components/ui/use-toast";

const initialSettings = {
  storage_provider: "Platform",
  storage_region: "",
  bucket_name: "",
  bucket_base_path: "/company/{env}/",
  signed_url_ttl_minutes: 60,
  exports_base_path: "exports/{timestamp}/",
  docs_base_paths: {
    invoices: "documents/invoices/{YYYY}/{MM}/",
    pos: "documents/pos/{YYYY}/{MM}/",
    dos: "documents/dos/{YYYY}/{MM}/",
    attachments: "documents/attachments/{YYYY}/{MM}/",
    books: "books/{YYYY}/"
  },
  db_auto_backup_enabled: true,
  db_backup_daily_hour_utc: 2,
  db_backup_retention_days: 60,
};

export default function StorageSettings({ currentUser }) {
  const [settings, setSettings] = useState(initialSettings);
  const [loading, setLoading] = useState(false);
  const [initialLoad, setInitialLoad] = useState(true);
  const { toast } = useToast();

  useEffect(() => {
    loadSettings();
  }, []);

  const loadSettings = async () => {
    try {
      const settingsList = await StorageSettingsEntity.list();
      if (settingsList.length > 0) {
        setSettings(settingsList[0]);
      }
    } catch (error) {
      console.error("Error loading storage settings:", error);
    } finally {
      setInitialLoad(false);
    }
  };

  const handleInputChange = (field, value) => {
    setSettings(prev => ({ ...prev, [field]: value }));
  };

  const handleSave = async () => {
    setLoading(true);
    try {
      const settingsList = await StorageSettingsEntity.list();
      if (settingsList.length > 0) {
        await StorageSettingsEntity.update(settingsList[0].id, settings);
      } else {
        await StorageSettingsEntity.create(settings);
      }
      await logAuditAction("StorageSettings", "singleton", "update", currentUser.email, { settings });
      toast({
        title: "Settings saved",
        description: "Storage and backup settings have been updated.",
      });
    } catch (error) {
      console.error("Error saving settings:", error);
      toast({ title: "Save failed", variant: "destructive" });
    } finally {
      setLoading(false);
    }
  };
  
  const handleTestConnectivity = async () => {
    setLoading(true);
    await logAuditAction("StorageSettings", "singleton", "test_connectivity", currentUser.email);
    toast({
      title: "Testing Connectivity...",
      description: "A connectivity test has been initiated. This is a backend process and results will be logged.",
    });
    // This is where a backend call would be made. We simulate a delay.
    setTimeout(() => {
      setLoading(false);
      toast({
        title: "Test Initiated",
        description: "The backend is performing the connectivity test.",
      });
    }, 2000);
  };

  const handleRunBackup = async () => {
    setLoading(true);
    await logAuditAction("StorageSettings", "singleton", "manual_db_backup", currentUser.email);
    toast({
      title: "Manual Backup Started",
      description: "A full SQL dump is being generated by the backend. You will be notified upon completion.",
    });
    // This is where a backend call would be made. We simulate a delay.
    setTimeout(() => {
      setLoading(false);
       toast({
        title: "Backup in Progress",
        description: "The backend is processing your request.",
      });
    }, 3000);
  };

  if (initialLoad) return <div>Loading settings...</div>;

  return (
    <Card className="border-0 shadow-lg">
      <CardHeader>
        <CardTitle>Storage & Backup</CardTitle>
        <CardDescription>Configure external storage, backup schedules, and document paths.</CardDescription>
      </CardHeader>
      <Tabs defaultValue="storage">
        <TabsList className="ml-6">
          <TabsTrigger value="storage">Storage Provider</TabsTrigger>
          <TabsTrigger value="paths">Document Paths</TabsTrigger>
          <TabsTrigger value="backups">Database Backups</TabsTrigger>
        </TabsList>
        <TabsContent value="storage" className="p-6 space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label>Storage Provider</Label>
                <Select value={settings.storage_provider} onValueChange={(v) => handleInputChange('storage_provider', v)}>
                  <SelectTrigger><SelectValue/></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="Platform">Platform (Default)</SelectItem>
                    <SelectItem value="S3">Amazon S3</SelectItem>
                    <SelectItem value="GCS">Google Cloud Storage</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label>Region</Label>
                <Input value={settings.storage_region} onChange={(e) => handleInputChange('storage_region', e.target.value)} placeholder="e.g., us-east-1" disabled={settings.storage_provider === 'Platform'}/>
              </div>
            </div>
             <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                    <Label>Bucket Name</Label>
                    <Input value={settings.bucket_name} onChange={(e) => handleInputChange('bucket_name', e.target.value)} placeholder="e.g., my-company-ops-bucket" disabled={settings.storage_provider === 'Platform'}/>
                </div>
                <div className="space-y-2">
                    <Label>Signed URL TTL (minutes)</Label>
                    <Input type="number" value={settings.signed_url_ttl_minutes} onChange={(e) => handleInputChange('signed_url_ttl_minutes', parseInt(e.target.value))}/>
                </div>
            </div>
            <div className="flex justify-end">
                <Button onClick={handleTestConnectivity} variant="outline" disabled={loading || settings.storage_provider === 'Platform'}>
                    <TestTube className="w-4 h-4 mr-2"/> Test Connectivity
                </Button>
            </div>
        </TabsContent>
        <TabsContent value="paths" className="p-6 space-y-6">
            <div className="space-y-2">
                <Label>Bucket Base Path</Label>
                <Input value={settings.bucket_base_path} onChange={(e) => handleInputChange('bucket_base_path', e.target.value)}/>
            </div>
            <div className="space-y-2">
                <Label>Exports Path</Label>
                <Input value={settings.exports_base_path} onChange={(e) => handleInputChange('exports_base_path', e.target.value)}/>
            </div>
            <div className="space-y-2">
                 <Label>Document Type Paths (JSON)</Label>
                 <Textarea
                    value={JSON.stringify(settings.docs_base_paths, null, 2)}
                    onChange={(e) => {
                        try {
                            const parsed = JSON.parse(e.target.value);
                            setSettings(prev => ({...prev, docs_base_paths: parsed }));
                        } catch (err) {
                            // handle invalid json
                        }
                    }}
                    rows={8}
                    className="font-mono text-sm"
                 />
            </div>
             <Card>
                <CardHeader><CardTitle className="text-base">Example Computed Paths</CardTitle></CardHeader>
                <CardContent className="text-xs text-gray-500 font-mono space-y-1">
                    <p><b>Invoice:</b> {settings.bucket_base_path}{settings.docs_base_paths.invoices}INV-2023-001.pdf</p>
                    <p><b>Purchase Order:</b> {settings.bucket_base_path}{settings.docs_base_paths.pos}PO-2023-001.pdf</p>
                </CardContent>
            </Card>
        </TabsContent>
        <TabsContent value="backups" className="p-6 space-y-6">
            <h3 className="text-lg font-semibold">Automated Backups</h3>
            <div className="flex items-center space-x-2">
              <Switch id="auto-backup-enabled" checked={settings.db_auto_backup_enabled} onCheckedChange={(c) => handleInputChange('db_auto_backup_enabled', c)}/>
              <Label htmlFor="auto-backup-enabled">Enable automated daily database backups</Label>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                 <div className="space-y-2">
                    <Label>Backup Hour (UTC)</Label>
                    <Input type="number" min="0" max="23" value={settings.db_backup_daily_hour_utc} onChange={(e) => handleInputChange('db_backup_daily_hour_utc', parseInt(e.target.value))}/>
                 </div>
                 <div className="space-y-2">
                    <Label>Backup Retention (days)</Label>
                    <Input type="number" min="1" value={settings.db_backup_retention_days} onChange={(e) => handleInputChange('db_backup_retention_days', parseInt(e.target.value))}/>
                 </div>
            </div>
            <h3 className="text-lg font-semibold mt-4">Manual Backup</h3>
            <div className="flex items-center gap-4">
                <Button onClick={handleRunBackup} disabled={loading}>
                    <Download className="w-4 h-4 mr-2" /> Run Full SQL Dump Now
                </Button>
            </div>
            <div className="mt-6">
                <h4 className="font-semibold mb-2">Recent Backups</h4>
                <div className="border rounded-md p-8 text-center text-gray-500">
                    <p>Backup list appears here.</p>
                    <p className="text-sm">This requires the backend backup service to be active.</p>
                </div>
            </div>
        </TabsContent>
      </Tabs>
      <CardFooter className="border-t pt-6">
        <div className="flex justify-end w-full">
            <Button onClick={handleSave} disabled={loading} className="bg-emerald-600 hover:bg-emerald-700">
                <Save className="w-4 h-4 mr-2"/>
                Save All Storage Settings
            </Button>
        </div>
      </CardFooter>
    </Card>
  );
}
